// 声明 proto 语法版本，固定值

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: goods/goods.proto

// proto 包名

package goods

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Types int32

const (
	Types_Defaults Types = 0
	Types_DianZi   Types = 20
	Types_LingShi  Types = 30
)

// Enum value maps for Types.
var (
	Types_name = map[int32]string{
		0:  "Defaults",
		20: "DianZi",
		30: "LingShi",
	}
	Types_value = map[string]int32{
		"Defaults": 0,
		"DianZi":   20,
		"LingShi":  30,
	}
)

func (x Types) Enum() *Types {
	p := new(Types)
	*p = x
	return p
}

func (x Types) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Types) Descriptor() protoreflect.EnumDescriptor {
	return file_goods_goods_proto_enumTypes[0].Descriptor()
}

func (Types) Type() protoreflect.EnumType {
	return &file_goods_goods_proto_enumTypes[0]
}

func (x Types) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Types.Descriptor instead.
func (Types) EnumDescriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{0}
}

type GoodsInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64   `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
	GoodsName  string  `protobuf:"bytes,20,opt,name=GoodsName,proto3" json:"GoodsName,omitempty"`
	GoodsPrice float32 `protobuf:"fixed32,30,opt,name=GoodsPrice,proto3" json:"GoodsPrice,omitempty"`
	GoodsNum   int64   `protobuf:"varint,40,opt,name=GoodsNum,proto3" json:"GoodsNum,omitempty"`
	GoodsType  Types   `protobuf:"varint,50,opt,name=GoodsType,proto3,enum=Goods.Types" json:"GoodsType,omitempty"`
}

func (x *GoodsInfo) Reset() {
	*x = GoodsInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_goods_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfo) ProtoMessage() {}

func (x *GoodsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_goods_goods_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfo.ProtoReflect.Descriptor instead.
func (*GoodsInfo) Descriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{0}
}

func (x *GoodsInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GoodsInfo) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *GoodsInfo) GetGoodsPrice() float32 {
	if x != nil {
		return x.GoodsPrice
	}
	return 0
}

func (x *GoodsInfo) GetGoodsNum() int64 {
	if x != nil {
		return x.GoodsNum
	}
	return 0
}

func (x *GoodsInfo) GetGoodsType() Types {
	if x != nil {
		return x.GoodsType
	}
	return Types_Defaults
}

// 定义商品修改的请求体
type GoodsUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Goods *GoodsInfo `protobuf:"bytes,1,opt,name=goods,proto3" json:"goods,omitempty"`
}

func (x *GoodsUpdateReq) Reset() {
	*x = GoodsUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_goods_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsUpdateReq) ProtoMessage() {}

func (x *GoodsUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_goods_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsUpdateReq.ProtoReflect.Descriptor instead.
func (*GoodsUpdateReq) Descriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{1}
}

func (x *GoodsUpdateReq) GetGoods() *GoodsInfo {
	if x != nil {
		return x.Goods
	}
	return nil
}

// 定义商品修改的响应体
type GoodsUpdateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Goods *GoodsInfo `protobuf:"bytes,1,opt,name=goods,proto3" json:"goods,omitempty"`
}

func (x *GoodsUpdateResp) Reset() {
	*x = GoodsUpdateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_goods_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsUpdateResp) ProtoMessage() {}

func (x *GoodsUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_goods_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsUpdateResp.ProtoReflect.Descriptor instead.
func (*GoodsUpdateResp) Descriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{2}
}

func (x *GoodsUpdateResp) GetGoods() *GoodsInfo {
	if x != nil {
		return x.Goods
	}
	return nil
}

// 定义商品创建的请求体
type GoodsCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Goods *GoodsInfo `protobuf:"bytes,1,opt,name=goods,proto3" json:"goods,omitempty"`
}

func (x *GoodsCreateReq) Reset() {
	*x = GoodsCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_goods_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsCreateReq) ProtoMessage() {}

func (x *GoodsCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_goods_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsCreateReq.ProtoReflect.Descriptor instead.
func (*GoodsCreateReq) Descriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{3}
}

func (x *GoodsCreateReq) GetGoods() *GoodsInfo {
	if x != nil {
		return x.Goods
	}
	return nil
}

// 定义商品创建的响应体
type GoodsCreateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Goods *GoodsInfo `protobuf:"bytes,1,opt,name=goods,proto3" json:"goods,omitempty"`
}

func (x *GoodsCreateResp) Reset() {
	*x = GoodsCreateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_goods_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsCreateResp) ProtoMessage() {}

func (x *GoodsCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_goods_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsCreateResp.ProtoReflect.Descriptor instead.
func (*GoodsCreateResp) Descriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{4}
}

func (x *GoodsCreateResp) GetGoods() *GoodsInfo {
	if x != nil {
		return x.Goods
	}
	return nil
}

type GetGoodsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int64 `protobuf:"varint,10,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Limit  int64 `protobuf:"varint,20,opt,name=Limit,proto3" json:"Limit,omitempty"`
}

func (x *GetGoodsReq) Reset() {
	*x = GetGoodsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_goods_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGoodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsReq) ProtoMessage() {}

func (x *GetGoodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_goods_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsReq.ProtoReflect.Descriptor instead.
func (*GetGoodsReq) Descriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{5}
}

func (x *GetGoodsReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetGoodsReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetGoodsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infos []*GoodsInfo `protobuf:"bytes,10,rep,name=Infos,proto3" json:"Infos,omitempty"`
	Total int64        `protobuf:"varint,20,opt,name=Total,proto3" json:"Total,omitempty"`
}

func (x *GetGoodsRes) Reset() {
	*x = GetGoodsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_goods_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGoodsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsRes) ProtoMessage() {}

func (x *GetGoodsRes) ProtoReflect() protoreflect.Message {
	mi := &file_goods_goods_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsRes.ProtoReflect.Descriptor instead.
func (*GetGoodsRes) Descriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{6}
}

func (x *GetGoodsRes) GetInfos() []*GoodsInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

func (x *GetGoodsRes) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetByIdGoodsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetByIdGoodsReq) Reset() {
	*x = GetByIdGoodsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_goods_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetByIdGoodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdGoodsReq) ProtoMessage() {}

func (x *GetByIdGoodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_goods_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdGoodsReq.ProtoReflect.Descriptor instead.
func (*GetByIdGoodsReq) Descriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{7}
}

func (x *GetByIdGoodsReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetByIdGoodsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *GoodsInfo `protobuf:"bytes,10,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *GetByIdGoodsRes) Reset() {
	*x = GetByIdGoodsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_goods_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetByIdGoodsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdGoodsRes) ProtoMessage() {}

func (x *GetByIdGoodsRes) ProtoReflect() protoreflect.Message {
	mi := &file_goods_goods_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdGoodsRes.ProtoReflect.Descriptor instead.
func (*GetByIdGoodsRes) Descriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{8}
}

func (x *GetByIdGoodsRes) GetInfo() *GoodsInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_goods_goods_proto protoreflect.FileDescriptor

var file_goods_goods_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x22, 0xa1, 0x01, 0x0a, 0x09, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4e,
	0x75, 0x6d, 0x18, 0x28, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4e,
	0x75, 0x6d, 0x12, 0x2a, 0x0a, 0x09, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x32, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x73, 0x52, 0x09, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x54, 0x79, 0x70, 0x65, 0x22, 0x38,
	0x0a, 0x0e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x26, 0x0a, 0x05, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x05, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x22, 0x39, 0x0a, 0x0f, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x05, 0x67,
	0x6f, 0x6f, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x22, 0x38, 0x0a, 0x0e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x05, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x22, 0x39, 0x0a,
	0x0f, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x26, 0x0a, 0x05, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x05, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x22, 0x3b, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x14, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x4b, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x52, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x05, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x0a, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x14, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x22, 0x21, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x37, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64,
	0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x2a, 0x2e,
	0x0a, 0x05, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x73, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x69, 0x61, 0x6e, 0x5a, 0x69, 0x10,
	0x14, 0x12, 0x0b, 0x0a, 0x07, 0x4c, 0x69, 0x6e, 0x67, 0x53, 0x68, 0x69, 0x10, 0x1e, 0x32, 0xfe,
	0x01, 0x0a, 0x0c, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x32, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x12, 0x12, 0x2e, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x1a,
	0x12, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73,
	0x52, 0x65, 0x73, 0x12, 0x3c, 0x0a, 0x0b, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x15, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x3c, 0x0a, 0x0b, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x12, 0x15, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x2e,
	0x47, 0x6f, 0x6f, 0x64, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x3e, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x12,
	0x16, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x2e,
	0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x42,
	0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x69,
	0x6e, 0x67, 0x67, 0x79, 0x79, 0x64, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f,
	0x67, 0x6f, 0x6f, 0x64, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_goods_goods_proto_rawDescOnce sync.Once
	file_goods_goods_proto_rawDescData = file_goods_goods_proto_rawDesc
)

func file_goods_goods_proto_rawDescGZIP() []byte {
	file_goods_goods_proto_rawDescOnce.Do(func() {
		file_goods_goods_proto_rawDescData = protoimpl.X.CompressGZIP(file_goods_goods_proto_rawDescData)
	})
	return file_goods_goods_proto_rawDescData
}

var file_goods_goods_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_goods_goods_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_goods_goods_proto_goTypes = []interface{}{
	(Types)(0),              // 0: Goods.Types
	(*GoodsInfo)(nil),       // 1: Goods.GoodsInfo
	(*GoodsUpdateReq)(nil),  // 2: Goods.GoodsUpdateReq
	(*GoodsUpdateResp)(nil), // 3: Goods.GoodsUpdateResp
	(*GoodsCreateReq)(nil),  // 4: Goods.GoodsCreateReq
	(*GoodsCreateResp)(nil), // 5: Goods.GoodsCreateResp
	(*GetGoodsReq)(nil),     // 6: Goods.GetGoodsReq
	(*GetGoodsRes)(nil),     // 7: Goods.GetGoodsRes
	(*GetByIdGoodsReq)(nil), // 8: Goods.GetByIdGoodsReq
	(*GetByIdGoodsRes)(nil), // 9: Goods.GetByIdGoodsRes
}
var file_goods_goods_proto_depIdxs = []int32{
	0,  // 0: Goods.GoodsInfo.GoodsType:type_name -> Goods.Types
	1,  // 1: Goods.GoodsUpdateReq.goods:type_name -> Goods.GoodsInfo
	1,  // 2: Goods.GoodsUpdateResp.goods:type_name -> Goods.GoodsInfo
	1,  // 3: Goods.GoodsCreateReq.goods:type_name -> Goods.GoodsInfo
	1,  // 4: Goods.GoodsCreateResp.goods:type_name -> Goods.GoodsInfo
	1,  // 5: Goods.GetGoodsRes.Infos:type_name -> Goods.GoodsInfo
	1,  // 6: Goods.GetByIdGoodsRes.info:type_name -> Goods.GoodsInfo
	6,  // 7: Goods.GoodsService.GetGoods:input_type -> Goods.GetGoodsReq
	2,  // 8: Goods.GoodsService.GoodsUpdate:input_type -> Goods.GoodsUpdateReq
	4,  // 9: Goods.GoodsService.GoodsCreate:input_type -> Goods.GoodsCreateReq
	8,  // 10: Goods.GoodsService.GetByIdGoods:input_type -> Goods.GetByIdGoodsReq
	7,  // 11: Goods.GoodsService.GetGoods:output_type -> Goods.GetGoodsRes
	3,  // 12: Goods.GoodsService.GoodsUpdate:output_type -> Goods.GoodsUpdateResp
	5,  // 13: Goods.GoodsService.GoodsCreate:output_type -> Goods.GoodsCreateResp
	9,  // 14: Goods.GoodsService.GetByIdGoods:output_type -> Goods.GetByIdGoodsRes
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_goods_goods_proto_init() }
func file_goods_goods_proto_init() {
	if File_goods_goods_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_goods_goods_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_goods_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_goods_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsUpdateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_goods_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_goods_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsCreateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_goods_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGoodsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_goods_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGoodsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_goods_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetByIdGoodsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_goods_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetByIdGoodsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_goods_goods_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_goods_goods_proto_goTypes,
		DependencyIndexes: file_goods_goods_proto_depIdxs,
		EnumInfos:         file_goods_goods_proto_enumTypes,
		MessageInfos:      file_goods_goods_proto_msgTypes,
	}.Build()
	File_goods_goods_proto = out.File
	file_goods_goods_proto_rawDesc = nil
	file_goods_goods_proto_goTypes = nil
	file_goods_goods_proto_depIdxs = nil
}
